### ISSUE TITLE
Version 0.5 does not work in Django 1.3.x

### ISSUE THREAD

**Issue by kveroneau** [jorgebastida/django-dajaxice#58]
File affected: dajaxice/templatetags/dajaxice_templatetags.py
Error: ImportError raised loading dajaxice.templatetags.dajaxice_templatetags: cannot import name staticfiles_storage

Version 0.5 appears to be only compatible with Django 1.4+

**Comment by jorgebastida** [comment]
Fixed. I've just releases django-dajaxice 0.5.1, should be fine now.

Thanks for the report!
